### ISSUE TITLE
create the review component

### ISSUE THREAD

**Issue by hbnnguyen** [JeffLi117/NomNomNavigator#16]

**Comment by XiandiPan** [comment]
In the Component/RestaurantReview.js:

1. Fetching place_id from the Google Places API.
2. Fetching Review Data by utilizing the obtained place_id to query a different API endpoint specifically for review data related to that place_id.
3. Displaying Review Data by rendering the fetched review data within the Review component, possibly using the SectionList component.

https://www.loom.com/share/eb2b2ec953084797a3662a1ea61a45d7?sid=59287018-5d8b-4055-a7a1-ca3f8c14858b
